<#
.SYNOPSIS
    Creates a full PowerShell module project scaffold.

.DESCRIPTION
    Generates a complete, professional PowerShell module structure including:
    - Public and Private function folders
    - Tests folder with Pester scaffolding
    - Docs folder for PlatyPS help
    - Analyzer folder with PSScriptAnalyzer settings
    - Scripts folder containing build/publish/documentation scripts
    - Module manifest and loader (.psd1 / .psm1)
    - Optional Git initialization
    Supports both CLI and GUI workflows for specifying the module name.

.PARAMETER Path
    The base directory where the module folder will be created.

.PARAMETER Name
    The name of the module. Used for folder creation, manifest generation,
    documentation, and all scaffolding components.

.PARAMETER UseGui
    Displays a GUI prompt to collect the module name. Overrides CLI input.

.PARAMETER InitGit
    Initializes a Git repository inside the generated module and creates a
    .gitignore file.

.EXAMPLE
    New-ModuleTemplate -Path "C:\Projects" -Name "MyModule"

.EXAMPLE
    New-ModuleTemplate -Path "C:\Projects" -UseGui

.NOTES
    - This is the orchestrator for all scaffolding functions.
    - Folder creation is handled by New-ModuleFolders.
    - The module loader is generated by New-ModuleLoader.
#>
function New-ModuleTemplate {
    [CmdletBinding(DefaultParameterSetName = "CLI")]
    param(
        # Path belongs to BOTH parameter sets
        [Parameter(ParameterSetName = "CLI", Mandatory = $true)]
        [Parameter(ParameterSetName = "GUI", Mandatory = $true)]
        [string]$Path,

        # Name belongs ONLY to CLI
        [Parameter(ParameterSetName = "CLI", Mandatory = $true)]
        [string]$Name,

        # UseGui belongs ONLY to GUI
        [Parameter(ParameterSetName = "GUI", Mandatory = $true)]
        [switch]$UseGui,

        # InitGit belongs to BOTH sets
        [Parameter(ParameterSetName = "CLI")]
        [Parameter(ParameterSetName = "GUI")]
        [switch]$InitGit
    )

    # GUI workflow: prompt for module name
    if ($UseGui) {
        $Name = Show-GuiPrompt -Prepopulate $Name -Path $Path
        if (-not $Name) { return }
    }

    # Create the module folder structure
    $base = New-ModuleFolders -Path $Path -Name $Name

    # Generate module components
    New-ModuleManifestFile     -BasePath $base -Name $Name
    New-ModuleLoader           -BasePath $base -Name $Name
    New-PesterTests            -BasePath $base -Name $Name
    New-AnalyzerSettings       -BasePath $base
    New-ModuleChangelog        -BasePath $base
    New-DocumentationScripts   -BasePath $base -Name $Name
    New-BuildScript            -BasePath $base -Name $Name
    New-PublishScript          -BasePath $base -Name $Name
    New-ModuleReadme           -BasePath $base -Name $Name

    # Optional Git initialization
    if ($InitGit) {
        Initialize-GitRepository -BasePath $base
    }

    Write-Host "Module '$Name' created at $base"
}
