name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              shell: pwsh
              run: |
                  pwsh -Command "Install-Module Pester -Scope CurrentUser -Force"
                  pwsh -Command "Install-Module PlatyPS -Scope CurrentUser -Force"
                  pwsh -Command "Install-Module PSScriptAnalyzer -Scope CurrentUser -Force"

            - name: Run build
              shell: pwsh
              run: pwsh ./Scripts/build.ps1
